intel_pmt_features.h: Add intel_pmt_features.h into copylist
intel_pmt_features headers has been introduced from 6.17 kernel.
Hence observing below error.
To fix this error, Add intel_pmt_features header into copylist.

Error:
---------------------------------------------------------------------------
fatal error: linux/intel_pmt_features.h: No such file or directory
---------------------------------------------------------------------------

Reference:
	86fc85c75bcd platform/x86/intel/pmt/discovery: Get telemetry attributes

Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>