backport/backport-include/linux: Backport from_work macro
from_work was introduced in workqueue headers (KV 6.9) but in
older kernels the macro is not available causing the compilation issue.

error:
-------------------------------------------------------------------------
implicit declaration of function from_work
-------------------------------------------------------------------------

So backport from_work macro in workqueue.h.

Reference:
    60b2ebf48526
    workqueue: Introduce from_work() helper for cleaner callback declarations

Signed-off-by: Nitin Gote <nitin.r.gote@intel.com>