Backport intel_vsec_register() api
intel_vsec_register(0 api is introduced from 6.8 kernel.
hence observing below error for 6.6 kernel.
To fix this error, backported complete intel_vsec_register() api.

Error:
-----------------------------------------------------------------------
error: conflicting types for ‘intel_vsec_register’;
have ‘void(struct pci_dev *, struct intel_vsec_platform_info *)’
-----------------------------------------------------------------------

Jira: VLK-80254

Reference:
	812bca7f7e73
	platform/x86:intel/vsec: Change return type of intel_vsec_register

Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>