backport: Add TAINT_TEST macro for kernel 5.15
Error:
- xe_lrc.c:1159:19: error: 'TAINT_TEST' undeclared

TAINT_TEST was added in kernel 5.18 for tainting test modules.
Define it as value 18 for kernel 5.15 compatibility.

Reference:
	2852ca7fba9f panic: Taint kernel if tests are run

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>