autotools/m4: backport drm_coredump_printer_is_full() api
drm_coredump_printer_is_full() api is introduced from 6.16 kernel.
Hence observing below error for 6.6 kernel.
To fix this error, backported drm_coredump_printer_is_full(0 api for
below 6.16 kernel.

Error:
-----------------------------------------------------------------------
error: implicit declaration of function ‘drm_coredump_printer_is_full’
-----------------------------------------------------------------------

Reference:
	fa4b8b3e3a11 drm/print: Add drm_coredump_printer_is_full

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>