autotools/m4: manage str_plural availability
str_plural was introduced in KV 6.9.0 onwards hence
enable the backport to avoid below error

Error:
----------------------------------------------------------
implicit declaration of function str_plural
---------------------------------------------------------

Reference:
    9ca5facd0400f lib/string_choices: Add str_plural() helper

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Signed-off-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>