Temp fix compat/iommu: Backport iommu_group_claim_dma_owner() api
iommu_group_claim_dma_owner() api is introduced from 5.19 kernel.
Hence below error is observing aginst 5.15 headers.
To fix this error, backported this api.

Error:
------------------------------------------------------------------------------
error: implicit declaration of function ‘iommu_group_claim_dma_owner’
------------------------------------------------------------------------------

Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>