backport/backport-include/linux: Backport disable_delayed_work_sync() api
disable_delayed_work_sync() was introduced in workqueue headers but in
older kernels the api is not available causing the compilation issue.

error:
-------------------------------------------------------------------------------
implicit declaration of function disable_delayed_work_sync
-------------------------------------------------------------------------------

So, added a conditional check where if disable_delayed_work_sync() api is
not present it will use native implementation cancel_delayed_work_sync()
api for older kernels.

Reference:
   86898fa6b8cd
   workqueue: Implement disable/enable for (delayed) work items

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>