autotools/m4: manage shrinker API changes
From KV 6.7 onwards, shrinker registration API changed from
register_shrinker() to shrinker_alloc()/shrinker_register()/shrinker_free()
in newer kernels.
Use m4 macro to detect API availability and provide compatibility.

Error:
--------------------------------------------------------------------------
error: implicit declaration of function 'shrinker_alloc'
error: implicit declaration of function 'shrinker_register'
error: implicit declaration of function 'shrinker_free'
--------------------------------------------------------------------------

Reference:
    d35b5c98c1f1 drm/ttm: dynamically allocate the drm-ttm_pool shrinker

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>