autotools/m4: manage DRM GPUVM symbol renaming for kernel 6.6
Kernel 6.6 has partial DRM GPUVM structures that conflict with our
complete backport, causing "redefinition of struct drm_gpuva_op_map"
compilation failures.

Implement automatic symbol renaming by using LINUX_BACKPORT() to resolve
DRM GPUVM redefinition errors when compiling XE driver on kernel 6.6.

Error:
-------------------------------------------------------------------------------
redefinition of _struct drm_gpuva_op_map_
redefinition of _struct drm_gpuva_op_unmap_
redefinition of _struct drm_gpuva_op_prefetch_
redefinition of _struct drm_gpuva_op_
-------------------------------------------------------------------------------

Reference:
    b06d47be7c83
    drm/xe: Port Xe to GPUVA

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>