eventfd.h: backport struct vfio_pci_eventfd for kernels missing it
struct vfio_pci_eventfd was removed or is not present in the 6.6
kernel, causing a compile failure when building the VFIO PCI backport:

Add the struct definition to the compat layer to restore the missing
type and allow vfio_pci_core.c to compile cleanly against 6.6 kernels.

Error:
------------------------------------------------------------------------------
error: too few arguments to function ‘eventfd_signal’
------------------------------------------------------------------------------

Reference:
	3652117f8548 eventfd: simplify eventfd_signal()

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>