autotools/m4: Backport DRM_GPUVA_OP_DRIVER enum member
DRM_GPUVA_OP_DRIVER enum member of enum drm_gpuva_op_type has been
introduced from 6.15 kernel.
Hence observing below error for 6.6 kernel.
To fix this error, backported DRM_GPUVA_OP_DRIVER enum member for below
6.15 kernel.

Error:
-----------------------------------------------------------------------
error: ‘DRM_GPUVA_OP_DRIVER’ undeclared
-----------------------------------------------------------------------

Reference:
	e53c1e263e5c drm/gpuvm: Add DRM_GPUVA_OP_DRIVER

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>