backport: Add num_pages_contiguous helper for kernel  5.15
Error:
- vfio_iommu_type1.c: undefined reference to 'num_pages_contiguous'

num_pages_contiguous() is a helper function added in kernel 6.6+
that counts the number of contiguous pages in an array.

Implement inline version that checks if pages are contiguous
by comparing their PFNs (Page Frame Numbers).

Reference:
	929bf010e059 mm: introduce num_pages_contiguous()

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>