drm/pagemap: Use zone_device_page_init() for zone device memory initialization
When zone_device_folio_init() is not present fallback to zone_device_page_init()
for zone device memory initialization.

While zone_device_folio_init() operates on compound folios directly,
zone_device_page_init() initializes a single struct page,
which corresponds to one base page

Limitations of fallback:
- No support for large folios (2MB, 1GB, etc.)
- Cannot efficiently handle 2MB+ contiguous zone device allocations
- Loss of huge page benefits and THP support

error:
-------------------------------------------------------------------------------
error: implicit declaration of function ‘zone_device_folio_init’; did you mean
          zone_device_folio_init((struct folio *)page, zdd->dpagemap->pagemap,

error: implicit declaration of function ‘folio_set_zone_device_data’; did you mean
          folio_set_zone_device_data(page_folio(page), drm_pagemap_zdd_get(zdd));
-------------------------------------------------------------------------------

Reference:
   d245f9b4ab80
   mm/zone_device: support large zone device private folios

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Pravalika Gurram <pravalika.gurram@intel.com>
(cherry picked from commit 735bd52159088a487965298eb10bd8e7f7ee1648)