autotools/m4: Probe for access_remote_vm and provide compat shim
Add a compatibility fallback in memory.c that provides
access_remote_vm() (and EXPORT_SYMBOL(access_remote_vm)) when the
probe indicates the symbol/function is not available.

The fallback:
Scans the process list under rcu_read_lock() to find a task_struct
with the target mm and then calls access_process_vm() on that task.

error:
--------------------------------------------------------------------------
ERROR: modpost: "access_remote_vm" [drivers/gpu/drm/xe/xe.ko] undefined!
--------------------------------------------------------------------------

Reference:
   5ddd36b9c
   mm: implement access_remote_vm

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>
(cherry picked from commit a8a65b8c14d443c48f1e4ced80bfcb548d82a20a)