backport-include/mm: manage vm_flags_set/clear/mod helpers for pre-6.3 kernels
vm_flags_set(), vm_flags_clear() and vm_flags_mod() were introduced in
linux v6.3 as helpers to modify vma->vm_flags. On base kernel 5.15 these
functions do not exist, causing implicit declaration errors. Add an m4
detection probe and provide inline macro fallbacks in backport-include.

Error:
-------------------------------------------------------------------------------
implicit declaration of function 'vm_flags_set'
-------------------------------------------------------------------------------

Reference:
  c1e3f1c611e6
  mm: introduce vm_flags_set/vm_flags_clear

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>