backports: Add intel_lb_mei_interface.h file
From KV 6.18 onwards, introduced new intel_lb_mei_interface.h header
file for late binding component driver.

Add intel_lb_mei_interface.h file in copy-list to resolve below error.

Error:
-------------------------------------------------------------------------------
error: drm/intel/intel_lb_mei_interface.h: No such file or directory
-------------------------------------------------------------------------------

Reference:
    741eeabb7c78
    mei: late_bind: add late binding component driver

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>