autotools/m4: manage FIELD_PREP_CONST availability
FIELD_PREP_CONST is introduced in 6.3 kernel.
define FIELD_PREP_CONST macro in bitfield.h backport header to
resolve below error.

Error:
implicit declaration of function ‘FIELD_PREP_CONST’

Reference:
    e2192de59e45 bitfield: add FIELD_PREP_CONST()

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>