backport-include/linux/dma-fence: handle the map from extern_lock to lock
On older kernels there is no inline locking mechanism available, but only
external lock is provided, so simply replace variable name of structure
from extern_lock to lock.

error:
-------------------------------------------------------------------------------
error: 'struct dma_fence' has no member named 'extern_lock';
-------------------------------------------------------------------------------

Reference:
   1f32f310a13c
   dma-buf: inline spinlock for fence protection v5

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Pravalika Gurram <pravalika.gurram@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>
(cherry picked from commit 425294ee2d8b7ce00b3d7c1c5abd32b7f9107669)