Don't use match_token_uuid for 6.6 kernel
struct vfio_device_ops has no member named ‘match_token_uuid’ for 6.6 kernel.
Hence observing below errors.
To fix these errors, don't use match_token_uuid and related function for
6.6 kernel.

Errors:
--------------------------------------------------------------------------------
error: ‘const struct vfio_device_ops’ has no member named ‘match_token_uuid’
error: initialization of ‘void (*)(struct vfio_device *, u64,  u64)’ {aka ‘
void (*)(struct vfio_device *, long long unsigned int,  long long unsigned int
)’} from incompatible pointer type ‘int (*)(struct vfio_device *, const uuid_t *)
--------------------------------------------------------------------------------

Reference:
	86624ba3b522 vfio/pci: Do vf_token checks for VFIO_DEVICE_BIND_IOMMUFD

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
coauthered-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>