compat: add pci_iov_vf_id() stub for pre-5.18 kernels
pci_iov_vf_id() was introduced in Linux 5.18 to provide a standard helper
returning the 0-based VF index for a PCI VF device, computed from
the SR-IOV First VF Offset and VF Stride fields in the PF's
extended capability space.
Building xe/main.c on kernels < 5.18 fails with error.
To fix build error, add pci_iov_vf_id() stub for pre-5.18 kernels in
compat layer.

Error:
----------------------------------------------------------------------------
error: implicit declaration of function ‘pci_iov_vf_id’
----------------------------------------------------------------------------

Reference:
	0e7df22401a3 PCI/IOV: Add pci_iov_vf_id() to get VF index

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>