autotools/m4: Add BPM_OBJTOOL_COPY_ATTRIBUTE_NEEDED
From kernel 6.15 and RHEL 10.1, objtool strictly validates
module init/exit functions and rejects the deprecated pattern of creating
init_module() and cleanup_module() via simple function aliasing.

Add BPM_OBJTOOL_COPY_ATTRIBUTE_NEEDED macro to enable objtool-compatible
module initialization using __copy() and ___ADDRESSABLE() attributes in
the module.h wrapper.

Error:
-----------------------------------------------------------------------
error: objtool: init_module(): Magic init_module() function
               name is deprecated
error: objtool: cleanup_module(): Magic cleanup_module()
               function name is deprecated
-----------------------------------------------------------------------

Reference:
  4fab2d7628dd ("objtool: Fix init_module() handling")

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>