autotools/m4: magane dma_fence_is_container() api availability for 5.15
dma_fence_is_container() was introduced in 5.18 and is not available on
5.15, causing implicit declaration errors in dma-fence-array compat code.

Fix by adding a fallback implementation in linux/dma-fence.h gated on
BPM_DMA_FENCE_IS_CONTAINER_NOT_PRESENT, detected at configure time.

Error:
implicit declaration of function 'dma_fence_is_container'

Reference:
976b6d97c623 ("dma-buf: consolidate dma_fence subclass checking")

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>