vfio/pci: define struct msi_map and MSI-X dynamic alloc stubs
struct msi_map and associated functions (pci_msix_alloc_irq_at,
pci_msix_can_alloc_dyn) were introduced in upstream kernel v6.2.

Add compat definitions guarded by macro in the backport MSI compat header,
alongside the pci_msix_alloc_irq_at stub.

Errors:
------------------------------------------------------------------------------
error: implicit declaration of function ‘pci_msix_alloc_irq_at’
error: implicit declaration of function ‘pci_msix_can_alloc_dyn’
------------------------------------------------------------------------------

Reference:
	34026364df8e
	PCI/MSI: Provide post-enable dynamic allocation interfaces for MSI-X

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>