autotools/m4: Manage VFIO_GET_REGION_INFO_CAPS availability
Implement compatibility layer for get_region_info_caps callback in
struct vfio_device_ops introduced in v7.0kv to support vfio-pci
operations on older kernels.

error:
-------------------------------------------------------------------------------
error: ‘const struct vfio_device_ops’ has no member named ‘get_region_info_caps’
-------------------------------------------------------------------------------

In 7.0kv get_region_info_caps introduced to call struct vfio_device_ops inorder
to enable drivers to provide custom region capability information. But in older
kernels this mechanism lack this callback member in the vfio_device_ops
structure.

So, implemented autoconf detection and conditional compilation to detect
get_region_info_caps member availability via struct compilation probe.

Reference:
   775f726a742a
   vfio: Add get_region_info_caps op

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>