Backport step.h header into backports tree
xe_step_types.h pulls in <drm/intel/step.h> for the enum intel_step definitions,
but that header was not being copied from the kernel tree into the
generated backports output because older kernels don't have it.
Hence backported step.h to fix the below compilation error.

Fatal error:
------------------------------------------------------------------------------
Error: drm/intel/step.h: No such file or directory
------------------------------------------------------------------------------

Reference:
	3ccc8a922906 drm/intel: add shared step.h and switch i915 to use it

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>