copy-list: Add aperture.h header for 5.15
aperture.h file is introduced in 6.0 kernel.

for 5.15 kernel, adding the aperture backport header to copy-list
so it is always included in generated/backport outputs and
available to Xe sources at build time.

Error:
fatal error: linux/aperture.h: No such file or directory

Reference:
7283f862bd99 (drm: Implement DRM aperture helpers under video/)

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>