autotools/m4: Backport drm_dev_wedged_event api
drm_dev_wedged_event() api is introduced from 6.15 kv.
Hence observing below error for below 6.15 kv.
To fix this error, backported complete drm_dev_wedged_event()
for below 6.15 kv.

Error:
-----------------------------------------------------------------------
error: implicit declaration of function ‘drm_dev_wedged_event’
-----------------------------------------------------------------------

Reference:
	b7cf9f4ac1b8 drm: Introduce device wedged event

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>