compat: add anon_inode_getfile_fmode() wrapper for pre-6.10 kernels
anon_inode_getfile_fmode() was introduced in Linux 6.10 as an extension
of anon_inode_getfile() that accepts an fmode_t argument to set file
mode flags at creation time.
Add a compat inline wrapper that falls back to anon_inode_getfile() and
manually applies the fmode flags post-creation:

Error:
------------------------------------------------------------------------------
error: implicit declaration of function ‘anon_inode_getfile_fmode’
------------------------------------------------------------------------------

Reference:
	55394d29c9e1 fs: Create anon_inode_getfile_fmode()

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>