iommu: Backport iommu_group_dma_owner_claimed() for kernels < 5.19
iommu_group_dma_owner_claimed() was introduced in Linux 5.19 as part of
the DMA ownership tracking model. On older kernels, the function does not
exist, causing the following build failure.
To fix this error, backport iommu_group_dma_owner_claimed() to compat/iommu.c
for kernels below 5.19.

Error:
------------------------------------------------------------------------------
error: implicit declaration of function ‘iommu_group_dma_owner_claimed’
------------------------------------------------------------------------------

Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>