backport-include: add folio helper functions in mm.h for 5.15 kernel
ttm_backup uses folio helper APIs that are missing on 5.15, causing
implicit declaration failures during build.

Fix by adding compat fallbacks in linux/mm.h for missing folio helpers,
mapping them to equivalent page-based helpers used on older kernels.

Error:
implicit declaration of function 'folio_put'
implicit declaration of function 'folio_mark_accessed'
implicit declaration of function 'folio_lock'
implicit declaration of function 'folio_mark_dirt
implicit declaration of function 'folio_mapped'
implicit declaration of function 'folio_clear_dirty_for_io'

Reference:
    b620f63358cd ("mm: Add folio_put()")

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>