Temp fix: slab.h: add missing linux/slab.h include
kfree() and kzalloc() are both declared in <linux/slab.h>.
When building vfio/group.c in the backport tree, the header is not pulled
in transitively, causing below errors.

Add an explicit #include <linux/slab.h> to resolve both implicit
declaration errors.

Error:
------------------------------------------------------------------------------
error: implicit declaration of function ‘kfree’
error: implicit declaration of function ‘kzalloc’
------------------------------------------------------------------------------

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>