autotools/m4: manage bin_attribute read member availability
Starting from kernel v6.14, struct bin_attribute member 'read'
was renamed to 'read_new'. Add conditional compilation to handle
both member names across kernel versions.

Fixes compilation errors when accessing bin_attribute read
callback member on different kernel versions.

Error:
-------------------------------------------------------------------------------
error: ‘struct bin_attribute’ has no member named ‘read_new’
-------------------------------------------------------------------------------

Reference:
    7ff2fecc8bc2
    platform/x86/intel/pmt: Constify 'struct bin_attribute'

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>