pagemap.h: Backport folio_next_index() api
folio_next_index() was introduced upstream in v5.16.
Older kernels has no struct folio and no folio_nr_pages().
Hence observing below errors during compilation aginst older kernels.
To fix this error, backport-include/linux/mm.h already treats a struct folio * as
a struct page * via casts.

Error:
-----------------------------------------------------------------------------
error: implicit declaration of function ‘folio_next_index’
-----------------------------------------------------------------------------

Reference:
	f94b18f6653a mm/filemap: Add folio_next_index()

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>