mm/migrate_device: disable THP migration if not supported
MIGRATE_PFN_COMPOUND and MIGRATE_VMA_SELECT_COMPOUND these flags enable compound
page representation in the migration array, allowing 2MB THP pages to be
migrated as a single unit to device memory.

Without this flag, the kernel has no way to signal "these 512 pages
belong together." Each 4KB page gets its own independent array entry,
and the driver treats them as 512 separate allocations.

Limitation:
  - Zone device memory fragmented into 4KB pages

error:
-------------------------------------------------------------------------------
error: ‘MIGRATE_PFN_COMPOUND’ undeclared (first use in this function)
error: ‘MIGRATE_VMA_SELECT_COMPOUND’ undeclared (first use in this function)
-------------------------------------------------------------------------------

Reference:
   a30b48bf1b2
   mm/migrate_device: implement THP migration of zone device pages

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Pravalika Gurram <pravalika.gurram@intel.com>
(cherry picked from commit 5c5322fb2484ef7fc79162b8a201f65e4738afcf)