drm/xe: Include nospec header for array_index_nospec
Since array_index_nospec() has been using in xe driver and defined in
nospec.h header file, For 6.17 current header files including nospec.h.
But for 6.6 LTS, We need to explicitly include header file into source.

Error:
-----------------------------------------------------------------------
error: implicit declaration of function ‘array_index_nospec’
-----------------------------------------------------------------------

Reference:
	f3804203306e array_index_nospec: Sanitize speculative array de-references

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>