autotools/m4: manage secs_to_jiffies prototype
Introduced secs_to_jiffies() function from KV 6.13 onwards,
which causes below issue.

Error:
-------------------------------------------------------------------------------
error: implicit declaration of function 'secs_to_jiffies'
-------------------------------------------------------------------------------

Backport secs_to_jiffies() using msecs_to_jiffies() to resolve it.

Reference:
    b35108a51cf7 jiffies: Define secs_to_jiffies()

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>