autotools/m4: Backport kmap_local_page_try_from_panic() function
kmap_local_page_try_from_panic() function is introduced from on 6.16 kernel.
Hence observing below error agsinst 6.6 kernel.
To fix this error, backported kmap_local_page_try_from_panic() function.

Error:
----------------------------------------------------------------------------
error: implicit declaration of function ‘kmap_local_page_try_from_panic’
----------------------------------------------------------------------------

Reference:
	8702048bb831 mm/kmap: Add kmap_local_page_try_from_panic()

Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>