autotools/m4: Add probe for vma_alloc_folio
Add probe to detect missing hugepage argument to satisfy older API.

error:
-------------------------------------------------------------------------
drm_pagemap.c:727: too few arguments to function 'vma_alloc_folio'
-------------------------------------------------------------------------

Reference:
   6359c39c9de6
   mm: remove unused hugepage for vma_alloc_folio()

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Varun Gupta <varun.gupta@intel.com>