autotools/m4: Manage init_llist_node interface prototype availability
Implemented compatibility layer for init_llist_node function introduced in
v6.7 kernel onwards to support DRM GPUVM lock-less list initialization.

error:
-------------------------------------------------------------------------------
implicit declaration of function ‘init_llist_head’
-------------------------------------------------------------------------------

The function init_llist_node() in v6.7 for proper initialization of
lock-less list nodes. The DRM GPUVM uses this to initialize deferred
BO list entries. So in v6.6 kernels lack this helper function. Therefore,
implemented autoconf to detect init_llist_node availability through llist.h
and provided inline implementation using WRITE_ONCE when unavailable.

Reference:
   d6b3358a2813
   llist: add interface to check if a node is on a list

Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>