autotools/m4: manage drmm_cgroup_register_region() prototype
The drmm_cgroup_register_region() api was introduced in KV 6.14.
A full implementation in backports would face significant
api compatibility and maintenance challenges across
multiple kernel versions. To avoid below error,

Error:
-------------------------------------------------------------------------------
error: implicit declaration of function _drmm_cgroup_register_region_
-------------------------------------------------------------------------------

Added NULL stub for function to enable xe driver compilation on
older kernels. xe handles NULL gracefully through "if (man->cg)"
checks, disabling cgroup memory accounting while preserving
core functionality.

Reference:
    7b0af165e2d4
    drm/drv: Add drmm managed registration helper for dmem cgroups.

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>