Add __assign_str macro gets the length of string
Implement compatibility layer for __assign_str tracing macro signature
change from 1 to 2 arguments that occurred between kernel versions to
support xe driver tracepoints across all target kernels.

error:
-------------------------------------------------------------------------------
error: macro "__assign_str" requires 2 arguments, but only 1 given __assign_str
       undeclared (first use in this function)
-------------------------------------------------------------------------------

The kernel tracing subsystem changed __assign_str macro signature between
versions. But in older kernels use single-argument form:__assign_str(field);

From v7.0 kernels require two-argument form with explicit source value:
  __assign_str(field, source_value);

Reference:
   c759e609030c
   tracing: Remove __assign_str_len()

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>
(cherry picked from commit a96c0a0ce4cb9f0314b8d0ae594a7be5c2015623)