fixup!: drm/xe: Backport pin_vram_percent module parameter
The reason of failure is the pin_vram_percent member of struct xe_modparam is
conditionally compiled under the macro BPM_DRMM_CGROUP_REGISTER_REGION_NOT_PRESENT.
However, in module param registeration it was earlier declared
unconditionally without guarding under the macro.

error:
-------------------------------------------------------------------------------
struct xe_modparam has no member named pin_vram_percent
-------------------------------------------------------------------------------

Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>