backport-include/linux/workqueue: provide fallback for system_dfl_wq() unavailability
The reason of introducing system_dfl_wq() is to encourage this workqueue
to be used as a default workqueue in place of or alongside
system_unbound_wq().

So wherever, system_dfl_wq() is not available fallback to system_unbound_wq().

error:
-------------------------------------------------------------------------------
error: 'system_dfl_wq' undeclared (first use in this function);
       did you mean 'system_unbound_wq'?
-------------------------------------------------------------------------------

Reference:
   128ea9f6ccfb
   workqueue: Add system_percpu_wq and system_dfl_wq

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Pravalika Gurram <pravalika.gurram@intel.com>