backport/compat: Add drm_dev_wedged_event compatibility
Provide a compatibility implementation of drm_dev_wedged_event for trees
that do not expose to the device-wedged uevent API or that use an
older three-argument signature. This allows backported DRM drivers and
helpers to emit the same device wedged uevent with the same environment
variables and semantics as upstream, even when building against older
kernels.

error:
-------------------------------------------------------------------------
ERROR: modpost: compat/xe-compat: 'drm_dev_wedged_event' exported twice.
-------------------------------------------------------------------------

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>
(cherry picked from commit 88ac9281384ba14bf99f05a4a14a76eaf2feed49)