autotools/m4: manage scope member availability in struct pmu
The perf subsystem in kernels below 6.14 does not support the scope member
in struct pmu, so device-wide PMU events are incorrectly treated as per-CPU.
This change introduces manual logic to restrict event handling to a single
CPU and handle CPU hotplug for system-wide PMU events in the Xe driver.

* Adds a static cpumask and target CPU variable to track the responsible CPU.
* Registers CPU hotplug callbacks to migrate the PMU context when the responsible
  CPU goes offline.
* Restricts perf events to only run on the chosen CPU in xe_pmu_event_init.
* Adds xe_pmu_init() and xe_pmu_exit() for hotplug callback registration and cleanup.

Error:
-------------------------------------------------------------------------------
drivers/gpu/drm/xe/xe_pmu.c:562:error:_struct pmu_ has no member named _scope_
  562 |         pmu->base.scope         = PERF_PMU_SCOPE_SYS_WIDE;
-------------------------------------------------------------------------------

Reference:
    4ba4f1afb6a9
    perf: Generic hotplug support for a PMU with a scope

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>