backport-include/linux/workqueue: add WQ_PERCPU stub
WQ_PERCPU is only called by alloc_workqueue(), eventhough we pass 0
wherever we don't have WQ_PERCPU as not defined, we will not have any
functional impact because in older kernels we WQ_PERCPU is not present.

We can't define the exact value because the flag is not part of __WQ_BH_ALLOWS
mask flag which is used for conditionally, rejecting the allocation of
workqueue.

error:
-------------------------------------------------------------------------------
error: 'WQ_PERCPU' undeclared (first use in this function);
       did you mean 'WQ_UNBOUND'?
-------------------------------------------------------------------------------

Reference:
   930c2ea566aff
   workqueue: Add new WQ_PERCPU flag

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>