autotools/m4: manage generic_handle_irq_safe() prototype availability
generic_handle_irq_safe() api is introduced in 5.18 kernel.

Backport generic_handle_irq_safe() api for 5.15 kernel to resolve
below error.

Error:
implicit declaration of function ‘generic_handle_irq_safe’

Reference:
    509853f9e1e7 genirq: Provide generic_handle_irq_safe()

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>