autotools/m4: Manage shmem_writeout() prototype availability
In v7.0-rc1 shmem_writeout() was renamed from shmem_writepage()
to shmem_writeout() as a simplified helper for writing shmem folios
to swap. The TTM backup module uses this for efficient memory reclaim
during buffer object swapping.

error:
-------------------------------------------------------------------------------
error: implicit declaration of function shmem_writeout(to_folio, NULL, NULL);
ERROR: modpost: "shmem_writeout" [~/src/drivers/gpu/drm/ttm/ttm.ko] undefined!
-------------------------------------------------------------------------------

Reference:
   7b73c12c6ebf0
   shmem: Add shmem_writeout()

Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>