backport: Add range_overflows and struct_size_t macros
Errors:
- drm_buddy.c:1035:21: error: implicit declaration of function 'range_overflows'
- linux/slab.h:152:35: error: implicit declaration of function 'struct_size_t'

range_overflows() checks if a range (start + size) would overflow past max.
Added in kernel 6.6+.

struct_size_t() calculates the size of a struct with a trailing variable array.
Like struct_size() but takes a type instead of pointer. Added in newer kernels.

Reference:
	5f3cec21f6d5 overflow: add range_overflows() and range_end_overflows()

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>