Move for_each_if() to util_macros.h for wider use
Other subsystem(s) may want to reuse the for_each_if() macro.
Move it to util_macros.h to make it globally available.

error:
--------------------------------------------------------------------------------
error: implicit declaration of function for_each_if(!(__entity) ||
                                         (__job)->entity == (__entity))
--------------------------------------------------------------------------------

The for_each_if macro was introduced to linux/util_macros.h for conditional
iteration filtering. DRM GPU scheduler uses this in
drm_sched_for_each_pending_job() iterator to filter jobs by entity.

Implemented autoconf detection to detect for_each_if availability via
util_macros.h compilation probe and define as conditional empty-block pattern
when unavailable.

Reference:
   b2108fc82a0a
   drm: Move for_each_if() to util_macros.h for wider use

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>
(cherry picked from commit 96b0ad51b1062646da000ea3a8d47ddc253a97f6)