autotools/m4: Add probe for zone_device_page_init
Add a probe to detect the legacy signature of zone_device_page_init().
When detected, a backport shim intercepts the modern call and safely
strips the unsupported arguments to satisfy the older kernel API.

error:
-------------------------------------------------------------------------
drm_pagemap.c:204: too many arguments to function 'zone_device_page_init'
-------------------------------------------------------------------------

Reference:
	1. 12b2285bf3d1
		mm/zone_device: reinitialize large zone device private folios
	2. d245f9b4ab80
		mm/zone_device: support large zone device private folios

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Varun Gupta <varun.gupta@intel.com>
(cherry picked from commit 923dddc9cd085509537742951f237569eedd6e10)