drm/ttm: stop updating nr_gpu_reclaim/active sys entries for gpu memory tracking
Wherever, NR_GPU_RECLAIM and NR_GPU_ACTIVE support in memzone is not available,
stop updating the entries.As memzone is a part of core kernel which cannot be
backported.

Limitations:

- /proc/meminfo will not show GPU memory tracking entries
- Per-node GPU allocation stats not available
- No visibility into TTM-allocated device memory from userspace
- System monitoring tools cannot track GPU memory pressure

With the above limitations there is no functional issue.

error:
-------------------------------------------------------------------------------
error: 'NR_GPU_RECLAIM' undeclared (first use in this function)
       mod_lruvec_page_state(p, reclaim ? NR_GPU_RECLAIM : NR_GPU_ACTIVE
error: 'NR_GPU_ACTIVE' undeclared (first use in this function)
       mod_lruvec_page_state(p, reclaim ? NR_GPU_RECLAIM : NR_GPU_ACTIVE
-------------------------------------------------------------------------------

Reference:
   ae80122f3896
   drm/ttm: use gpu mm stats to track gpu memory allocations.

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Pravalika Gurram <pravalika.gurram@intel.com>
(cherry picked from commit 129d9c2f82bc99fdeca522eafb6032d6b5b2b4d4)