autotools/m4: Use shmem_writepage instead of shmem_writeout
shmem_writepage() api is replaced by shmem_writeout() from 6.16 kernel.
Hence observing shmem_writeout api missing error against 6.6 LTS.
To fix this error, call writepage function pointer which calls
shmem_writepage() api when shmem_writeout() api is not present.

Error:
-----------------------------------------------------------------------------
error: implicit declaration of function ‘shmem_writeout’
-----------------------------------------------------------------------------

Reference:
	84798514db50 mm: Remove swap_writepage() and shmem_writepage()

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>