autotools/m4: manage local64_try_cmpxchg prototype availability
local64_try_cmpxchg in introduced in 6.4 kernel.

backport local64_try_cmpxchg for 5.15 kernel to resolve below error.

Error:
implicit declaration of function ‘local64_try_cmpxchg’

Reference:
    8fc4fddaf9a1 locking/generic: Wire up local{,64}_try_cmpxchg()

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>