mei: bus: fix uevent const argument compatibility
When compiling mei bus driver for older kernels, the mei_cl_device_uevent()
function signature is incompatible with newer kernels where
struct bus_type.uevent requires const struct device_driver *.
This causes a compilation error on older kernels.

Add conditional compilation to support both older kernels with
non-const parameter and newer kernels with const parameter.

Error:
-------------------------------------------------------------------------------
initialization of ‘int (*)(struct device *, struct kobj_uevent_env )’ from
incompatible pointer type ‘int ()(const struct device *,
struct kobj_uevent_env *)’
.uevent = mei_cl_device_uevent,
-------------------------------------------------------------------------------

Reference:
   2a81ada32f0e
   driver core: make struct bus_type.uevent() take a const *

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>