autotools/m4: manage origin member availability in struct drm_printer
From KV 6.11 onwards, origin member is added in drm_printer
structure to improve drm dev printk function output.

manage origin member availability by using m4 function if origin
member is not available in struct drm_printer.

Error:
-------------------------------------------------------------------------------
struct drm_printer has no member named origin
-------------------------------------------------------------------------------

Reference:
    c2ef66e9ad88
    drm/print: Improve drm_dbg_printer

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>