backport/backport-include/linux: manage FIELD_PREP_CONST availability
FIELD_MODIFY is introduced in 6.16 kernel.
define FIELD_MODIFY macro in bitfield.h backport header to
resolve below error.

Error:
   implicit declaration of function FIELD_MODIFY

Reference:
    a256ae22570e bitfield: Add FIELD_MODIFY() helper

Signed-off-by: Nitin Gote <nitin.r.gote@intel.com>