iommu: backport iommu_group dma ownership APIs
Three functions required by VFIO to enforce exclusive software
ownership of IOMMU groups during SR-IOV VF assignment to guests:

  - iommu_group_claim_dma_owner(group, owner)
  - iommu_group_release_dma_owner(group)
  - iommu_group_dma_owner_claimed(group)

Multiple devices may be placed in the same IOMMU group because they cannot be
isolated from each other. These devices must be entirely under kernel control.
This adds dma ownership management in iommu core and exposes several interfaces
for the device drivers, so that any conflict between user and kernel
controlled dma could be detected at the beginning.
Since structure iommu_group is private structure of iommu driver that needs to
be accessed in compat layer which is not feasible.

Errors:
------------------------------------------------------------------------------
error: implicit declaration of function ‘iommu_group_claim_dma_owner’
error: implicit declaration of function ‘iommu_group_release_dma_owner’
error: implicit declaration of function ‘iommu_group_dma_owner_claimed’
------------------------------------------------------------------------------

Reference:
	1ea2a07a532b iommu: Add DMA ownership management interfaces

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>