autotools/m4: backport bits header macros
GENMASK_U* and BIT_U32 macros have been defined from 6.16 kernel.
Hence observing below errors.
To fix these errors, backported GENMASK_U* and BIT_U32 macros
for 6.6 kernel.

Errors:
-----------------------------------------------------------------------
error: implicit declaration of function ‘GENMASK_U32’
error: implicit declaration of function ‘GENMASK_U64’
error: implicit declaration of function ‘BIT_U32’
-----------------------------------------------------------------------

Reference:
	19408200c094 bits: introduce fixed-type GENMASK_U*()

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>