copy-list: add kunit visibility.h header file
kunit visibility.h header is introduced in 6.1 kernel.

Add kunit visibility.h to resolve below error.

Error:
fatal error: kunit/visibility.h: No such file or directory

Reference:
    9c988fae6f6a
    kunit: add macro to allow conditionally exposing static symbols to tests

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>