backport: Inline dma_fence_check_and_signal_locked() in dma-fence.h
v7.0 added dma_fence_check_and_signal_locked() as a small inline-able
helper that checks DMA_FENCE_FLAG_SIGNALED_BIT and then calls
dma_fence_signal_locked(). On <v7.0 we previously provided this as an
out-of-line symbol in compat/dma-fence.c; move it to a static inline
in backport-include/linux/dma-fence.h so consumers do not depend on a
compat module symbol.

Drops the now-empty compat/dma-fence.c.

-----------------------------------------------------------------
error: xe_hw_fence.c:93: implicit declaration of function
	'dma_fence_check_and_signal_locked'
-----------------------------------------------------------------

Reference:
	c891b99d25
	dma-buf/dma-fence: Add dma_fence_check_and_signal()

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Varun Gupta <varun.gupta@intel.com>