backport-include/linux/list_lru: provide backport compatability for list_lru_add_obj()
Newer kernels renamed this to list_lru_add_obj(lru, item) and
introduced a new 4-argument list_lru_add() as the main interface. On old kernels,
the new name simply does not exist, so any code calling list_lru_add_obj() fails
to build.

error:
-------------------------------------------------------------------------------
error: implicit declaration of function 'list_lru_add_obj'
-------------------------------------------------------------------------------

Reference:
   0a97c01cd20
   list_lru: allow explicit memcg and NUMA node selection

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>