autotools/m4: manage drm_exec_init prototype
Introduced 3rd argument for drm_exec_init() api from kv 6.8,
which causes below issue.

Error:
-------------------------------------------------------------------------------
error: too many arguments to function _drm_exec_init_
-------------------------------------------------------------------------------

Backport drm_exec_init() with 2 arguments for 6.6 KV to resolve it.

Reference:
    05d249352f1a drm/exec: Pass in initial # of objects

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>