backport: Add device coherent page and folio API  compatibility
Errors:
- drm_gpusvm.c:827:21: error: implicit declaration of function 'is_device_coherent_page'
- drm_pagemap.c:247:25: error: implicit declaration of function 'page_folio'
- drm_pagemap.c:248:25: error: implicit declaration of function 'folio_order'
- drm_pagemap.c:732:33: error: implicit declaration of function 'vma_alloc_folio'
- drm_pagemap.c:737:33: error: implicit declaration of function 'folio_alloc'
- drm_pagemap.c:742:24: error: implicit declaration of function 'folio_page'
- drm_pagemap.c:761:31: error: implicit declaration of function 'folio_trylock'

Device coherent pages are not supported in kernel 5.15.
is_device_coherent_page() added as stub returning false.

Folio APIs were introduced in kernel 5.16+. Added macro backports
that cast folios to/from struct page for compatibility.

Reference:
	bd0dbbb3fd90 mm: reimplement folio_is_device_coherent()

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Co-authored-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>
Signed-off-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>