backport-include/gpu_buddy: rename gpu_buddy to drm_buddy
This is purely rename gpu_buddy to drm_buddy, with no functional impact.
In latest kernel DRM_BUDDY moved to top-level gpu folder, and all the
api's renamed FROM DRM_BUDDY to GPU_BUDDY. This was done for non-drm
users.

On older kernel where buddy is still part of drm itself, just use
DRM_BUDDY.

error:
-------------------------------------------------------------------------------
error: ‘GPU_BUDDY_CONTIGUOUS_ALLOCATION’ undeclared (first use in this function)
-------------------------------------------------------------------------------

Reference:
   ba110db8e1bc
   gpu: Move DRM buddy allocator one level up (part two)

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Pravalika Gurram <pravalika.gurram@intel.com>
(cherry picked from commit cce1bb8f8cc049be2ff3a4e2a8e45428ca75e2db)