drm/ttm: provide fallaback implementation for take_one_from_lru() and pool_move_to_dispose_list()
With prior to the referenced commit locking model where isolation required
holding the list_lru global node lock, which was passed explicitly to the
callback and had to be held on exit (__must_hold(lock)).

In mainline kernel the implementation moved to a per-cgroup lock embedded inside
list_lru_one(). Since the lock is now always the one associated with the
list_lru_one, there is no need to pass it separately.

error:
-------------------------------------------------------------------------------
error: incompatible pointer type when assigning 'take_one_from_lru' to
       type 'list_lru_walk_cb' [-Werror=incompatible-pointer-types]
error: incompatible pointer type when assigning 'pool_move_to_dispose_list' to
       type 'list_lru_walk_cb' [-Werror=incompatible-pointer-types]
-------------------------------------------------------------------------------

Reference:
   da0c02516c50
   mm/list_lru: simplify the list_lru walk callback function

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>