autotools/m4: manage drm_print_hex_dump() prototype
drm_print_hex_dump() api is introduced in kv 6.17.
Backport drm_print_hex_dump() api to resolve below
error for older kernels.

Error:
--------------------------------------------------------------------------
error: implicit declaration of function drm_print_hex_dump
--------------------------------------------------------------------------

Reference:
    3050c1811387
    drm/print: add drm_print_hex_dump()

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>