drm: fix drm_gem_ttm_vmap/vunmap signature for pre-5.18 kernels
On kernels older than 5.18, iosys-map did not exist and the mapping
type was struct dma_buf_map. Gate the vmap/vunmap function signatures
in both the header and source on HAVE_LINUX_IOSYS_MAP_H so the
declaration and definition always match.

Error:
conflicting types for 'drm_gem_ttm_vmap'; have 'int(struct drm_gem_object *,
struct iosys_map *)'

Reference:
7938f4218168
dma-buf-map: Rename to iosys-map

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>