Include slab.h in fs.h
kfree and kzalloc are defined in slab.h and included from fs.h
But fs.h in not including slab.h till 5.18 KV
Hence observing below errors.
To fix these errors, included slab.h into fs.h based on slb.h is
included or not.

Error:
------------------------------------------------------------------------------
error: implicit declaration of function ‘kfree’
error: implicit declaration of function ‘kzalloc’
------------------------------------------------------------------------------

Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>