autotools/m4: manage list_count_nodes() prototype availability
list_count_nodes() api is introduced in 6.3 kernel.

Backport list_count_nodes() api in list.h header for 5.15 kernel to
resolve below error.

Error:
implicit declaration of function ‘list_count_nodes’

Reference:
    4d70c74659d9
    i915: Move list_count() to list.h as list_count_nodes() for broader use

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>