autotools/m4: Manage DRM_DEV_WEDGED_EVENT_NOT_PRESENT availability
Add a BPM_DRM_WEDGE_TASK_INFO_NOT_PRESENT probe to detect device wedged
event/support so the backport build can adapt when the kernel provides the interface.
Update the backport of drm_device.h to match API/uevent fields and helper
definitions used by the wedged-device flow.

error:
----------------------------------------------------
error: redefinition of struct drm_wedge_task_info
----------------------------------------------------

Reference:
   e41315787dda
   drm: Add missing struct drm_wedge_task_info kernel doc

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>
(cherry picked from commit a9bb86a08f219ebebf8992ca0e523a611820fd37)