fix redefinition of struct pci_sriov between backport header and xe_pci_sriov.c
struct pci_sriov was defined in both backport-include/linux/pci.h
and locally in xe_pci_sriov.c:116, causing below error.

Fix by guarding structure definitions with BACKPORT_STRUCT_PCI_SRIOV_DEFINED
and remove pci_sriov struct definitiion from xe_pci_sriov.c and get it from
backported pci.h header file.

Error:
-------------------------------------------------------------------------------
error: redefinition of 'struct pci_sriov'
-------------------------------------------------------------------------------

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>