autotools/m4: manage dma_resv_for_each_fence() api availability
dma_resv_for_each_fence() was introduced in Linux 5.16.
Add autotools detection and use a backport fallback path for older
kernels (such as 5.15) where the API is not present.

Error:
-------------------------------------------------------------------------------
implicit declaration of function dma_resv_for_each_fence
-------------------------------------------------------------------------------

Reference:
    5baaac3184ab
    dma-buf: add dma_resv_for_each_fence v3

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>