autotools/m4: manage drmm_alloc_ordered_workqueue prototype
drmm_alloc_ordered_workqueue() api is introduced in kv 6.15.
Backport drmm_alloc_ordered_workqueue() api to resolve below
error for older kernels.

Error:
-------------------------------------------------------------------------------
error: implicit declaration of function ‘drmm_alloc_ordered_workqueue’
-------------------------------------------------------------------------------

Reference:
    c367b772e6d8
    drm/managed: Add DRM-managed alloc_ordered_workqueue

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>