drm/xe: use single-pass MMU notifier when invalidate_start/finish not present
mmu_interval_notifier_ops {invalidate_start/invalidate_finish}
is used for two-pass communication, if those are not presnet,
fall back to single-pass synchronous invalidation.

The two-pass interface enables parallel TLB invalidation across multiple tiles.
The key function xe_tlb_inval_range_tilemask_submit() iterates per-tile using
for_each_tile() and submits a TLB invalidation fence to each tile's primary_gt
(and media_gt if present) without blocking. The wait happens later in
xe_tlb_inval_batch_wait() which iterates all collected fences.

Performance limitation if we use single-pass:
  - multi-GPU will not have parallel gains in performance
  - cannot separate submission from waiting
  - single-GPU no impact as invalidation start and finish will be
    serial.

How performence issue will be seen for Multi GPU:
------------------------------------------
(two-pass):
    invalidate_start() → submit fence to GPU-A // ~0us
    invalidate_start() → submit fence to GPU-B // ~0us
    invalidate_start() → submit fence to GPU-C // ~0us
    invalidate_finish() → wait for All fences // ~50us

(single-pass fallback):
    invalidate() → submit + wait for fence GPU-A // ~50us
    invalidate() → submit + wait for fence GPU-B // ~50us
    invalidate() → submit + wait for fence GPU-C // ~50us

error:
-------------------------------------------------------------------------------
error: const struct mmu_interval_notifier_ops has no member named ‘invalidate_start’;
did you mean ‘invalidate’?
error: const struct mmu_interval_notifier_ops has no member named ‘invalidate_finish’
-------------------------------------------------------------------------------

Reference:
   7aba71dbc416
   mm/mmu_notifier: Allow two-pass struct mmu_interval_notifiers

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Pravalika Gurram <pravalika.gurram@intel.com>
(cherry picked from commit c3d57eadaf7c1166f801ace7fe5d871fff15b242)