Disable VFIO_PCI_DMABUF for kernel 5.15
Errors:
- vfio_pci_dmabuf.c:36:47: error: invalid use of undefined type 'struct dma_buf'
- vfio_pci_dmabuf.c:58:16: error: implicit declaration of function 'dma_buf_phys_vec_to_sgt'
- vfio_pci_dmabuf.c:88:21: error: variable 'vfio_pci_dmabuf_ops' has initializer but incomplete type
- vfio_pci_core.c: implicit declaration of function 'pcim_p2pdma_init'
- vfio_pci_dmabuf.c: implicit declaration of function 'pcim_p2pdma_provider'

VFIO_PCI_DMABUF requires APIs and structures not available in kernel 5.15:
- struct dma_buf and dma_buf_ops have different members
- dma_buf_phys_vec_to_sgt() function doesn't exist
- struct phys_vec is not defined

Disable this feature for kernel 5.15 by setting config to 'def_bool n'.

Also Managed P2PDMA (Peer-to-Peer DMA) API was added in same reference.
Kernel 5.15 does not have these functions.
Add stub implementations that return -EOPNOTSUPP (pcim_p2pdma_init)
and NULL (pcim_p2pdma_provider) since P2PDMA is not supported.

Reference:
	5d74781ebc86 vfio/pci: Add dma-buf export support for MMIO regions

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Co-authored-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>
Signed-off-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>