autotools/m4: manage alloc_ordered_workqueue_lockdep_map prototype
The alloc_ordered_workqueue_lockdep_map() function was introduced in
kernel v6.12 to support lockdep dependency tracking for ordered workqueues.
This causes compilation failures when building against 6.6 kernels where the
function doesn't exist.

Error:
-------------------------------------------------------------------------------
implicit declaration of function 'alloc_ordered_workqueue_lockdep_map'
-------------------------------------------------------------------------------

Add a compatibility wrapper that maps alloc_ordered_workqueue_lockdep_map()
to the standard alloc_ordered_workqueue() function for older kernels.

Reference:
    34f50cc6441b
    drm/sched: Use drm sched lockdep map for submit_wq

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>