autotools/m4: Add DRM_MODE_SIZE_DUMB prototype availability
Add a compatibility macro for drm_warn_once() which is not available
in older kernel versions e.g in 6.12kv and below. The fallback implementation
uses dev_warn_once() to provide equivalent functionality.

This resolves compilation errors in drm_dumb_buffers.c and other files that
use drm_warn_once() when building against kernels that don't provide this
macro natively.

error:
-------------------------------------------------------------------------------
error: implicit declaration of function ‘drm_warn_once’; drm_warn_once(dev,
modpost: "drm_mode_size_dumb" [~/src/drivers/gpu/drm/xe/xe.ko] undefined!
-------------------------------------------------------------------------------

Reference:
   fb6c7ab8718e
   drm/print: introduce new struct drm_device based logging macros

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>