autotools/m4: Manage DMA_FENCE_CHECK_AND_SIGNAL_LOCKED signals availability
In v7.0-rc1 kernel onwards dma_fence_check_and_signal_locked() was introduced
as an atomic operation that checks if a fence is already signaled
and signals it if not, all while holding the fence lock. The XE driver
uses this for hardware fence cleanup paths.

error:
------------------------------------------------------------------------
implicit declaration of function ‘dma_fence_check_and_signal_locked’;
           XE_WARN_ON(dma_fence_check_and_signal_locked(&fence->dma));
------------------------------------------------------------------------

Implementation:
- Detect dma_fence_check_and_signal_locked availability via compilation probe
- Provide implementation combining test_signaled_flag and signal_locked
- Export symbol for module usage
- Declare function prototype in backport header

Reference:
   c891b99d25dd
   dma-buf/dma-fence: Add dma_fence_check_and_signal()

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>
(cherry picked from commit b39830aa39fb06dce5400acc3de784a9800d596e)