backport-include/linux/gpu_buddy: add gpu_buddy_allocated_addr_to_block fallback
gpu_buddy_allocated_addr_to_block() was introduced as a helper for GPU buddy
manager. So the kernels using the older interface for drm_buddy will
lack with this helper, causing the compilation error.

error:
-------------------------------------------------------------------------------
error: implicit declaration of function gpu_buddy_allocated_addr_to_block
-------------------------------------------------------------------------------

Therefore, added no-ops with drm_buddy mappings which will maintain the
backport compatability against the older kernels.

Reference
   151ebbc20aa2
   drm/gpu: Add gpu_buddy_allocated_addr_to_block helper

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>