backport-include/bitmap: backport bitmap_weighted_or()
error:
-------------------------------------------------------------------------------
implicit declaration of function 'bitmap_weighted_or'
  [-Werror=implicit-function-declaration]
-------------------------------------------------------------------------------

Reference:
   437cb3ded250
   cpumask: Introduce cpumask_weighted_or()

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Pravalika Gurram <pravalika.gurram@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>