autotools/m4: Backport __drmm_workqueue_release() api
__drmm_workqueue_release() api is introduced from 6.15 kernel.
Hence observing below error for below 6.15 kernel.
To resolve this error, backported __drmm_workqueue_release api.

Error:
-----------------------------------------------------------------------
error: ‘__drmm_workqueue_release’ undeclared
-----------------------------------------------------------------------

Reference:
	c367b772e6d8 drm/managed: Add DRM-managed alloc_ordered_workqueue

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>