iommu: backport iommu_paging_domain_alloc() for kernels < 6.11
iommu_paging_domain_alloc() was introduced in Linux 6.11 as an explicit
API for allocating a paging-type IOMMU domain, replacing the more generic
iommu_domain_alloc(). On older kernels, the function does not exist and
causing the following build failure.
Backport iommu_paging_domain_alloc() to compat/iommu.c for kernels
below 6.11, implemented as a wrapper around iommu_domain_alloc(dev->bus),
which is the functional equivalent on older kernels where all allocated
domains are implicitly paging domains.

Error:
------------------------------------------------------------------------------
error: implicit declaration of function ‘iommu_paging_domain_alloc’
------------------------------------------------------------------------------

Reference:
	a27bf2743cb8 iommu: Add iommu_paging_domain_alloc() interface

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>