backport-include: backport kunit_get_current_test() api for 5.15
kunit_get_current_test() was introduced in 5.16.
On older kernels there is never an active KUnit test, return NULL.

Error:
implicit declaration of function ‘kunit_get_current_test’

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>