autotools/m4: manage PCI IOV VF BAR function apis
Add compatibility stubs for pci_iov_vf_bar_get_sizes() and
pci_iov_vf_bar_set_size() functions introduced in kernel 6.17.

The stubs return safe defaults allowing xe driver compilation on older
kernels while preserving SR-IOV functionality with fixed VF BAR sizes.

Error:
-------------------------------------------------------------------------------
error: implicit declaration of function _pci_iov_vf_bar_get_sizes_
error: implicit declaration of function _pci_iov_vf_bar_set_size_
-------------------------------------------------------------------------------

Reference:
    84f890414a12
    PCI/IOV: Allow drivers to control VF BAR size

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>