Backport shmem_writeout() function
shmem_writepage() function is renamed as shmem_writeout() and
writepage() is not exported in 6.6 kernel.
Hence observing below error.
To fix this error, backported shmem_writeout/shmem_writepage function.

Error:
-----------------------------------------------------------------------------
error: implicit declaration of function ‘shmem_writeout’
-----------------------------------------------------------------------------

Reference:
	7b73c12c6ebf shmem: Add shmem_writeout()

Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>