backport-include/linux: Add fallback for missing str_up_down helper
In kernels which provides string_choices headers but only provides a
few subset of helper functions. The problem is as str_plural() and str_up_down()
are not defined the BPM_STR_PLURAL_NOT_PRESENT macro was enabled which solely
includes to utilize the native headers.

So, when the function is called by xe_gt_idle.c and the fallback implementation
is not present or available on native header then it warns with an error:
-------------------------------------------------------------------------------
implicit declaration of function ‘str_up_down’
-------------------------------------------------------------------------------

Fixed this by including the native header implementation whenever
HAVE_LINUX_STRING_CHOICES_H is defined, and providing individual fallback
implementations guarded by their respective macros
BPM_STR_PLURAL_NOT_PRESENT and BPM_STR_UP_DOWN_NOT_PRESENT.

Reference:
    a98ae7f045b2 lib/string_choices: Add str_up_down() helper
    f5c1ca3a15fd string_choices: Add wrapper for str_down_up()
    9ca5facd0400 lib/string_choices: Add str_plural() helper

Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>