backport-include: Add generic drm_line_printer api backport support
drm_line_printer introduced in 6.13, needed for xe oot driver
on older kernels.

Original fallback used drm_debug_printer() which is deprecated/missing
in 6.12, causing below error:

Error:
-------------------------------------------------------------------------------
implicit declaration of function 'drm_debug_printer'
-------------------------------------------------------------------------------

Generic implementation using context structure to replicate native
6.13 behavior with series.counter format, depending only on basic
drm_printf() available across all kernel versions.

Reference:
    754e707e20e4
    drm/print: Introduce drm_line_printer

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>