vfio/pci: backport: add missing <linux/irq.h> include for IRQ_DISABLE_UNLAZY
IRQ_DISABLE_UNLAZY is defined in <linux/irq.h>. In upstream kernels,
this header is pulled in transitively, but when backporting
vfio_pci_intrs.c to older kernels the include chain have differed,
leaving IRQ_DISABLE_UNLAZY undeclared at the call site in the
MSI interrupt setup path.

Add an explicit #include <linux/irq.h> in the backport compat layer to
fix the build failure on kernels that do not pull in this header transitively.

Error:
------------------------------------------------------------------------------
error: ‘IRQ_DISABLE_UNLAZY’ undeclared
error: implicit declaration of function ‘irq_set_status_flags’
error: implicit declaration of function ‘irq_clear_status_flags’
------------------------------------------------------------------------------

Reference:
	e9849777d0e2 genirq: Add flag to force mask in disable_irq[_nosync]()

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>