autotools/m4: support register_shrinker for multiple kernels
The register_shrinker() function has different signatures across kernel
versions: 5.15 uses 1-arg form while 6.0+ expose 2-arg form. Add a probe
to detect this variation and gate the call appropriately.

Error:
error: too many arguments to function 'register_shrinker'

Reference:
e33c267ab70d ("mm: shrinkers: provide shrinkers with names")

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>