Backport parse_int_array_user() compat
parse_int_array_user() parses an array of integers from a userspace
buffer. This function is not available on older kernels.

Provide a backport implementation in compat/string_helpers.c, gated by
the BPM_PARSE_INT_ARRAY_USER_NOT_PRESENT config check, so the SR-IOV PF
debugfs write path builds and works on older kernels.

error: implicit declaration of function 'parse_int_array_user'

Reference:
    f0b933236ec97 lib/string_helpers: Introduce parse_int_array_user()

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>