autotools/m4: Manage PCI ReBAR helpers prototype availability
Below are the compilation issues which are faced while compiling against 6.6
headers

error:
-------------------------------------------------------------------------------
error: too many arguments to function pci_resize_resource(pdev, resno,
                                         bar_size, 0);
error: implicit declaration of function pci_rebar_size_supported,
       pci_rebar_size_to_bytes,  pci_rebar_get_max_size
-------------------------------------------------------------------------------

Extended pci_resize_resource() from 3 to 4 arguments in v6.19, adding an
exclude_bars parameter to control which BARs should be excluded from resizing.
The xe driver uses the 4-argument form for PCBAR expansion. But in older
kernels only support the 3-argument form without the exclude_bars parameter.

Similarly, there are three another compilation issues those are
  - pci_rebar_size_supported() - validate if size is supported for BAR
  - pci_rebar_size_to_bytes() - convert size encoding to byte values
  - pci_rebar_get_max_size() - query maximum supported BAR size

Implementation:
- pci_resize_resource: detect pci_resize_resource 4-argument support via
  compilation probe
- pci_rebar_size_supported: check if size is in supported bitmap
- pci_rebar_size_to_bytes: convert encoding to bytes using bit shift
- pci_rebar_get_max_size: find highest set bit in size bitmap

Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>