autotools/m4: manage auxiliary_get_drvdata api availability
auxiliary_get_drvdata and auxiliary_set_drvdata apis are
introduced in 5.17 kernels. backport these apis to resolve below error.

Error:
-------------------------------------------------------------------------------
implicit declaration of function ‘auxiliary_get_drvdata’
implicit declaration of function ‘auxiliary_set_drvdata’
-------------------------------------------------------------------------------

Reference:
    365481e42a8a
    driver core: auxiliary bus: Add driver data helpers

Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>