autotools/m4: manage drm_dbg_printer availability
Add a wrapper to switch from drm_dbg_printer() to drm_debug_printer() if
drm_dbg_printer is not available in the base kernel.

Error:
-------------------------------------------------------------------------------
implicit declaration of function _drm_dbg_printer_
-------------------------------------------------------------------------------

Reference:
    e7835e023f84
    drm/xe: switch from drm_debug_printer() to device specific drm_dbg_printer()

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>