Fix module symbols import issue
xe-vfio-pci driver needs symbols from xe gpu driver but it's not import
them. Hence observing below errors.
To fix these errors, imported xe-vfio-pci symbols.

Errors:
-----------------------------------------------------------------------------
ERROR: modpost: module xe-vfio-pci uses symbol xe_sriov_vfio_stop_copy_enter
from namespace module:xe-vfio-pci, but does not import it.
ERROR: modpost: module xe-vfio-pci uses symbol xe_sriov_vfio_stop_copy_exit
from namespace module:xe-vfio-pci, but does not import it.
ERROR: modpost: module xe-vfio-pci uses symbol xe_sriov_vfio_suspend_device
from namespace module:xe-vfio-pci, but does not import it.
----------------------------------------------------------------------------

Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>