compat: add anon_inode_getfile_fmode() backport wrapper
anon_inode_getfile_fmode() was introduced in Linux 6.10 as a convenience
wrapper around anon_inode_getfile() that additionally sets caller-specified
f_mode bits on the returned file. Kernels prior to 6.10 lack this helper.

Add a compat implementation that:
  1. Calls the existing anon_inode_getfile() to create the anon inode file
  2. ORs the caller-provided f_mode into file->f_mode on success
  3. Exports the symbol via EXPORT_SYMBOL_GPL for use by dependent modules

This unblocks compilation of upstream drivers that rely on
anon_inode_getfile_fmode() on kernels older than 6.10.

Error:
------------------------------------------------------------------------------
error: implicit declaration of function ‘anon_inode_getfile_fmode’
------------------------------------------------------------------------------

Reference:
	55394d29c9e1 fs: Create anon_inode_getfile_fmode()

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>