autotools/m4: manage dma_fence_array_alloc availability
dma_fence_array_create was converted to two different functions
dma_fence_array_alloc and dma_fence_array_init in KV6.12. use older API
for older versions.

Error:
--------------------------------------------------------------------------
error: implicit declaration of function _dma_fence_array_alloc
error: implicit declaration of function _dma_fence_array_init
--------------------------------------------------------------------------

Reference:
    ddc94d0b17e8
    dma-buf: Split out dma fence array create into alloc and arm functions

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Signed-off-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>