mei/csc: Add backport compatibility for pcim_iomap_region
pcim_iomap_region() was introduced in linux v6.12, while older kernels
provide pcim_iomap_regions() and pcim_iomap_table(). Use the older
managed mapping api when the newer helper is unavailable.

Error:
-------------------------------------------------------------------------------
implicit declaration of function ‘pcim_iomap_region’
-------------------------------------------------------------------------------

Reference:
   d140f80f6035
   PCI: Deprecate pcim_iomap_regions() in favor of pcim_iomap_region()

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>