mei: bus: fix match callback const argument compatibility
When compiling mei bus driver for older kernels, the mei_cl_device_match()
function signature is incompatible with newer kernels where
struct bus_type.match requires const struct device_driver *.
This causes a compilation error on older kernels.

Add conditional compilation to support both older kernels with
non-const parameter and newer kernels with const parameter.

Error:
-------------------------------------------------------------------------------
initialization of ‘int (*)(struct device *, struct device_driver *)’ from
incompatible pointer type ‘int (*)(struct device *, const struct
device_driver *)’ [-Werror=incompatible-pointer-types]
.match          = mei_cl_device_match
-------------------------------------------------------------------------------

Reference:
    d69d80484598
    driver core: have match() callback in struct bus_type take a const *

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>