autotools/m4: Use access_process_vm instead of access_remote_vm
access_remote_vm() is getting used in eudebug for VM access.
But access_remote_vm() is not exported and hence observing below error.
To fix this error, used access_process_vm() instead of
access_remote_vm() by converting mm_struct into task_struct.

Error:
-----------------------------------------------------------------------
ERROR: modpost: "access_remote_vm" undefined!
-----------------------------------------------------------------------

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>