autotools/m4: Add probe for folio_free
Add a probe to handle folio_free by using older
page based allocation.

error:
-------------------------------------------------------------------------
drm_pagemap.c:1170: 'dev_pagemap_ops' has no member named 'folio_free'
-------------------------------------------------------------------------

Reference:
	3a5a06554566
	mm/zone_device: rename page_free callback to folio_free

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Varun Gupta <varun.gupta@intel.com>
(cherry picked from commit 79a479656e133360ca5730ae8b68c8690fa3287d)