backport-include/linux/dma-fence: backport for dma_fence_lock_irqsave and restore()
In older kernels fence locking was performed directly through the underlying
spinlock primitives e.g spin_lock_irqsave() and spin_unlock_irqrestore().

Create a wrapper for both apis.

error:
-------------------------------------------------------------------------------
error: implicit declaration of function 'dma_fence_lock_irqsave'
error: implicit declaration of function 'dma_fence_unlock_irqrestore'
-------------------------------------------------------------------------------

Reference:
   3e5067931b
   dma-buf: abstract fence locking v2

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>
(cherry picked from commit e31ccc3fc17170cf16af32c61e9b55e6f78d4c00)