Add a callback to determine attribute visibility
Implement compatibility layer for configfs_group_operations.is_visible
member introduced in upstream 6.12 kernels to allow dynamic visibility
control of configfs attributes. This uses this for controlling
visibility of device and SR-IOV configuration groups based on device
capabilities.

error:
-----------------------------------------------------------------------------
error: ‘struct configfs_group_operations’ has no member named ‘is_visible’
        .is_visible     = xe_config_device_is_visible,
-----------------------------------------------------------------------------

So implemeted and conditional probe if is_visible member availability via
struct then include member assignment only when supported but member isn't
assigned on old kernels which holds original implementation.

Reference:
   0e6a35b93745bb
   fs/configfs: Add a callback to determine attribute visibility

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>
(cherry picked from commit 6ca101c988758a910988c7cc561b4c161feb4c62)