bitmap: Provide bitmap_weighted_or compatibility for 7.1KV
In 7.1 kernel code bitmap_weighted_or() to combine two bitmaps and return
the resulting weight in a single pass. So when the target is compiled
against ubuntu_7.0, below error is being observed.

error:
-------------------------------------------------------------------------------
ERROR: modpost: "__bitmap_weighted_or" [drivers/gpu/drm/xe/xe.ko] undefined!
-------------------------------------------------------------------------------

Therefore created a compatibility implementation in backport include bitmap
header:
   - perform bitmap_or(dst, src1, src2, nbits)
   - return bitmap_weight(dst, nbits)

Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>