autotools/m4: manage bin_attribute callback const parameter availability
Starting from kernel v6.14, bin_attribute callback functions now
expect a const struct bin_attribute * parameter.

The mmap callback signature changed:
Before (< v6.14):
int (*mmap)(struct file *, struct kobject *,
            struct bin_attribute *, ...)

After (>= v6.14):
int (*mmap)(struct file *, struct kobject *,
            const struct bin_attribute *, ...)

Add conditional compilation to support both old and new
callback signatures, ensuring compatibility across kernel versions.

Error:
-------------------------------------------------------------------------------
error: assignment to ‘int (*)(struct file *, struct kobject *, struct
bin_attribute *, struct vm_area_struct *)’ from incompatible pointer type
‘int (*)(struct file *, struct kobject *,
const struct bin_attribute *, struct vm_area_struct *)
-------------------------------------------------------------------------------

Reference:
    94a20fb9af16
    sysfs: treewide: constify attribute callback of bin_attribute::mmap()

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>