autotools/m4: manage str_up_down availability
str_up_down was moved under header file string_choices.h in
KV 6.12 onwards, manage unavailability using m4 function.

Error:
----------------------------------------------------------
implicit declaration of function str_up_down
---------------------------------------------------------

Reference:
    a98ae7f045b2 lib/string_choices: Add str_up_down() helper

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>