drm/xe: Handle DRM_BUDDY_CONTIGUOUS_ALLOCATION flag with fallback for older kernels
On older kernels CONTIGUOUS_ALLOCATION flag is not present, to handle its usage
provided a fallback: round up the allocation size to the next power
of two and trim the resulting blocks via drm_buddy_block_trim() to
satisfy contiguous allocation requests.

error:
-------------------------------------------------------------------------------
error: ‘DRM_BUDDY_CONTIGUOUS_ALLOCATION’ undeclared (first use in this function)
-------------------------------------------------------------------------------

Reference:
   dc2fc00ba94de
   drm/xe: Use DRM_BUDDY_CONTIGUOUS_ALLOCATION for contiguous allocations

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Pravalika Gurram <pravalika.gurram@intel.com>
(cherry picked from commit 6102a4357d887d6ba1b7e2628c084f4b5e3b6d96)