autotools/m4: Use hrtimer_init() instead of hrtimer_setup
hrtimer_setup() is introduced to replace hrtimer_init() from 6.13 kernel.
Hence observing below error for 6.6 kernel.
To fix this error, called hrtimer_init from hrtimer_setup() api.

Error:
-----------------------------------------------------------------------
error: implicit declaration of function ‘hrtimer_setup’
-----------------------------------------------------------------------

Reference:
	908a1d775422
	hrtimers: Introduce hrtimer_setup() to replace hrtimer_init()

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>