drm_ras_genl_family: Add DRM RAS module information
drm_ras is built as a standalone backport module. Add the required module
information to the DRM RAS Generic Netlink source so modpost can process
drm_ras.ko.

error:
-------------------------------------------------------------------------------
ERROR: modpost: missing MODULE_LICENSE() in src/drm_ras.o
-------------------------------------------------------------------------------

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>