autotools/m4: manage drm_line_printer availability
drm_line_printer is introduced in KV 6.13.

Add a wrapper to switch from drm_line_printer() to drm_debug_printer()
if drm_line_printer is not available in the base kernel.

Error:
-------------------------------------------------------------------------------
implicit declaration of function drm_line_printer
-------------------------------------------------------------------------------

Reference:
    754e707e20e4
    drm/print: Introduce drm_line_printer

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>