compat: backport follow_pfnmap_start/end() apis for pre-6.12 kernels
struct follow_pfnmap_args and follow_pfnmap_start()/follow_pfnmap_end()
were introduced in Linux 6.12 as a replacement for the follow_pfn() API.

Add a compat struct definition and inline follow_pfnmap_start()/end()
wrappers that delegate to follow_pfn() under a macro check.

Errors:
------------------------------------------------------------------------------
error: implicit declaration of function ‘follow_pfnmap_start’
error: implicit declaration of function ‘follow_pfnmap_end’
error: variable ‘args’ has initializer but incomplete type
error: ‘struct follow_pfnmap_args’ has no member named ‘vma’
error: ‘struct follow_pfnmap_args’ has no member named ‘address’
error: ‘struct follow_pfnmap_args’ has no member named ‘writable’
error: ‘struct follow_pfnmap_args’ has no member named ‘addr_mask’
error: storage size of ‘args’ isn’t known
------------------------------------------------------------------------------

Reference:
	6da8e9634bb7 mm: new follow_pfnmap API

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>