autotools/m4: backport pm_suspend_in_progress macro
pm_suspend_in_progress() macro has been introduced from 6.16 kernel.
Hence observing below error for 6.6 kernel.
To fix this error, backported pm_suspend_in_progress() macro.

Error:
-----------------------------------------------------------------------
error: implicit declaration of function ‘pm_suspend_in_progress’
-----------------------------------------------------------------------

Reference:
	34a364ff04e9 PM: sleep: Introduce pm_suspend_in_progress()

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>