autotools/m4: manage drm_dbg_ratelimited availability
drm_dbg_ratelimited was introduced in KV 6.9.0 onwards hence
enable the backport to avoid below error.

Error:
-------------------------------------------------------------------------------
implicit declaration of function drm_dbg_ratelimited
-------------------------------------------------------------------------------

Reference:
    20f5583dd7a5
    drm/print: Add drm_dbg_ratelimited

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>