drm/pagemap: handle folio_split member unavailability
- If struct dev_pagemap_ops doesnt have folio_split callback
  dont use it.
- If folio_split callback is not available — THP must not
  be supported.

Limitation:
  - Folio split notifications are not delivered to the driver, reference
    count safety and use-after-free protection introduced by this
    callback are unavailable

error:
-------------------------------------------------------------------------------
error: ‘const struct dev_pagemap_ops’ has no member named ‘folio_split’
-------------------------------------------------------------------------------

Reference:
   56ef398996435
   mm/memremap: add driver callback support for folio splitting

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Pravalika Gurram <pravalika.gurram@intel.com>
(cherry picked from commit 292f5e7b579318d55a17e0add7e272323e942fd8)