FIXME: trace: Make code compatible for older assign_str arguments
After changing assign_str to one argument in KV6.10, backporting to
older version need to change parameters with in trace definition.
Go back to old handling.

Error:
--------------------------------------------------------------------------
error: macro "__assign_str" requires 2 arguments, but only 1 given
--------------------------------------------------------------------------

Reference:
    2c92ca849fcc
    tracing/treewide: Remove second parameter of __assign_str()

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Signed-off-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>