backport-include/linux/dma-buf: provide flag handling for .invalidate_mappings()
The dma_buf_ops callback struct move_notify() function pointer has been
replaced by invalidate_mappings() in the latest kernel. Replace
invalidate_mappings() with move_notify() from the caller.

No functional impact with replacement.

error:
-------------------------------------------------------------------------------
error: 'struct dma_buf_attach_ops' has no member named 'invalidate_mappings'
-------------------------------------------------------------------------------

Reference:
   ef246da8e63c4
   dma-buf: Rename .move_notify() callback to a clearer identifier

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>